# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13training_data.proto\x12\x0bPersistence\",\n\x0bNdArrayData\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\r\"k\n\x15\x45valuationExampleData\x12(\n\x06inputs\x18\x01 \x01(\x0b\x32\x18.Persistence.NdArrayData\x12(\n\x06labels\x18\x02 \x01(\x0b\x32\x18.Persistence.NdArrayData\"G\n\x11\x45valuationDataSet\x12\x32\n\x06values\x18\x01 \x03(\x0b\x32\".Persistence.EvaluationExampleData\"R\n\x19\x43lassificationExampleData\x12(\n\x06inputs\x18\x01 \x01(\x0b\x32\x18.Persistence.NdArrayData\x12\x0b\n\x03\x63ls\x18\x02 \x01(\r\"`\n\x15\x43lassificationDataSet\x12\x36\n\x06values\x18\x01 \x03(\x0b\x32&.Persistence.ClassificationExampleData\x12\x0f\n\x07\x63lasses\x18\x02 \x01(\rb\x06proto3')



_NDARRAYDATA = DESCRIPTOR.message_types_by_name['NdArrayData']
_EVALUATIONEXAMPLEDATA = DESCRIPTOR.message_types_by_name['EvaluationExampleData']
_EVALUATIONDATASET = DESCRIPTOR.message_types_by_name['EvaluationDataSet']
_CLASSIFICATIONEXAMPLEDATA = DESCRIPTOR.message_types_by_name['ClassificationExampleData']
_CLASSIFICATIONDATASET = DESCRIPTOR.message_types_by_name['ClassificationDataSet']
NdArrayData = _reflection.GeneratedProtocolMessageType('NdArrayData', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAYDATA,
  '__module__' : 'training_data_pb2'
  # @@protoc_insertion_point(class_scope:Persistence.NdArrayData)
  })
_sym_db.RegisterMessage(NdArrayData)

EvaluationExampleData = _reflection.GeneratedProtocolMessageType('EvaluationExampleData', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONEXAMPLEDATA,
  '__module__' : 'training_data_pb2'
  # @@protoc_insertion_point(class_scope:Persistence.EvaluationExampleData)
  })
_sym_db.RegisterMessage(EvaluationExampleData)

EvaluationDataSet = _reflection.GeneratedProtocolMessageType('EvaluationDataSet', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONDATASET,
  '__module__' : 'training_data_pb2'
  # @@protoc_insertion_point(class_scope:Persistence.EvaluationDataSet)
  })
_sym_db.RegisterMessage(EvaluationDataSet)

ClassificationExampleData = _reflection.GeneratedProtocolMessageType('ClassificationExampleData', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONEXAMPLEDATA,
  '__module__' : 'training_data_pb2'
  # @@protoc_insertion_point(class_scope:Persistence.ClassificationExampleData)
  })
_sym_db.RegisterMessage(ClassificationExampleData)

ClassificationDataSet = _reflection.GeneratedProtocolMessageType('ClassificationDataSet', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONDATASET,
  '__module__' : 'training_data_pb2'
  # @@protoc_insertion_point(class_scope:Persistence.ClassificationDataSet)
  })
_sym_db.RegisterMessage(ClassificationDataSet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NDARRAYDATA._serialized_start=36
  _NDARRAYDATA._serialized_end=80
  _EVALUATIONEXAMPLEDATA._serialized_start=82
  _EVALUATIONEXAMPLEDATA._serialized_end=189
  _EVALUATIONDATASET._serialized_start=191
  _EVALUATIONDATASET._serialized_end=262
  _CLASSIFICATIONEXAMPLEDATA._serialized_start=264
  _CLASSIFICATIONEXAMPLEDATA._serialized_end=346
  _CLASSIFICATIONDATASET._serialized_start=348
  _CLASSIFICATIONDATASET._serialized_end=444
# @@protoc_insertion_point(module_scope)
