from nn.loss_functions.loss_function import LossFunction
from nn.loss_functions.mse_loss_function import MseLossFunction
from nn.loss_functions.cross_entropy_loss_function import CrossEntropyLossFunction
